package com.braymond.summarizer.model;

import java.time.OffsetDateTime;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;

@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public record GitHubRepo(
        long id,
        String nodeId,
        String name,
        String fullName,
        @JsonProperty("private") Boolean isPrivate,
        GitHubUser owner,
        String htmlUrl,
        String description,
        Boolean fork,
        String url,
        String forksUrl,
        String keysUrl,
        String collaboratorsUrl,
        String teamsUrl,
        String hooksUrl,
        String issueEventsUrl,
        String eventsUrl,
        String assigneesUrl,
        String branchesUrl,
        String tagsUrl,
        String blobsUrl,
        String gitTagsUrl,
        String gitRefsUrl,
        String treesUrl,
        String statusesUrl,
        String languagesUrl,
        String stargazersUrl,
        String contributorsUrl,
        String subscribersUrl,
        String subscriptionUrl,
        String commitsUrl,
        String gitCommitsUrl,
        String commentsUrl,
        String issueCommentUrl,
        String contentsUrl,
        String compareUrl,
        String mergesUrl,
        String archiveUrl,
        String downloadsUrl,
        String issuesUrl,
        String pullsUrl,
        String milestonesUrl,
        String notificationsUrl,
        String labelsUrl,
        String releasesUrl,
        String deploymentsUrl,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt,
        OffsetDateTime pushedAt,
        String gitUrl,
        String sshUrl,
        String cloneUrl,
        String svnUrl,
        String homepage,
        int size,
        int stargazersCount,
        int watchersCount,
        String language,
        Boolean hasIssues,
        Boolean hasProjects,
        Boolean hasDownloads,
        Boolean hasWiki,
        Boolean hasPages,
        Boolean hasDiscussions,
        int forksCount,
        String mirrorUrl,
        Boolean archived,
        Boolean disabled,
        int openIssuesCount,
        License license,
        Boolean allowForking,
        Boolean isTemplate,
        Boolean webCommitSignoffRequired,
        List<String> topics,
        String visibility,
        int forks,
        int openIssues,
        int watchers,
        String defaultBranch) {

    @JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
    public record License(
            String key,
            String name,
            String spdxId,
            String url,
            String nodeId) {
    }
}
